I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/endetermination.rpy", line 31, in script
    results = [True, True, True, True, True]
  File "game/endetermination.rpy", line 31, in <module>
    results = [True, True, True, True, True]
NameError: name 'checkFlaws' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/endetermination.rpy", line 31, in script
    results = [True, True, True, True, True]
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\ast.py", line 882, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/endetermination.rpy", line 31, in <module>
    results = [True, True, True, True, True]
NameError: name 'checkFlaws' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Dogging Sim 1.0
Sat Dec 08 00:20:22 2018
