I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/home.rpy", line 32, in script
    menu:
  File "game/home.rpy", line 33, in <module>
    "Play the three-cup game with [dog.name]" if not "cup" in home_done:
NameError: name 'home_done' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/home.rpy", line 32, in script
    menu:
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\ast.py", line 1562, in execute
    choice = renpy.exports.menu(choices, self.set)
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\exports.py", line 878, in menu
    if renpy.python.py_eval(condition) ]
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/home.rpy", line 33, in <module>
    "Play the three-cup game with [dog.name]" if not "cup" in home_done:
NameError: name 'home_done' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Dogging Sim 1.0
Sun Dec 02 15:21:45 2018
