I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/home.rpy", line 9, in script
    $if dogs.traits.social <= 2 or dog.traits.jealous >= 4: owner.traits.loyalty += 0.5
  File "game/home.rpy", line 9, in <module>
    $if dogs.traits.social <= 2 or dog.traits.jealous >= 4: owner.traits.loyalty += 0.5
AttributeError: 'DogTraits' object has no attribute 'jealous'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/home.rpy", line 9, in script
    $if dogs.traits.social <= 2 or dog.traits.jealous >= 4: owner.traits.loyalty += 0.5
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\ast.py", line 882, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/home.rpy", line 9, in <module>
    $if dogs.traits.social <= 2 or dog.traits.jealous >= 4: owner.traits.loyalty += 0.5
AttributeError: 'DogTraits' object has no attribute 'jealous'

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Dogging Sim 1.0
Sun Dec 02 19:09:34 2018
