I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/park.rpy", line 200, in script
    b "Woof!"
Exception: Sayer 'b' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/park.rpy", line 200, in script
    b "Woof!"
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Kirsten Pilla\Documents\renpy-7.1.1-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'b' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Dogging Sim 1.0
Sun Dec 09 12:46:57 2018
